# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Initialisation des données
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
spring.cache.redis.cache-null-values=false
#spring.cache.type=none

# Swagger UI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Spring Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus,caches
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Movie Management System
info.app.description=A Spring Boot application for managing movies
info.app.version=1.0.0

# Configuration du serveur
server.port=8080